name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  http: ^1.4.0
  cloud_firestore: ^5.6.9
  loading_overlay: ^0.4.2
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  get: ^4.7.2
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  intl: ^0.20.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0
  velocity_x: ^4.3.1
  shimmer: ^3.0.0
  pdf: ^3.11.3
  audioplayers: ^6.5.0
  flutter_webrtc: ^0.14.2
  lottie: ^3.3.0
  cloud_functions: ^5.6.1
  external_path: ^2.2.0
  open_file: ^3.5.10
  share_plus: ^11.0.0
  image_cropper: ^9.1.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2
  crop_your_image: ^2.0.0
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:

  color: "#C9253B"

  image: "assets/images/admin.png"

  android: true

  ios: true



  android_12:

    image: "assets/images/admin.png"

    icon_background_color: "#C9253B"

    image_dark: "assets/images/admin.png"

    icon_background_color_dark: "#C9253B"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/admin.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/images/bottom.png
    - assets/images/top.png
    - assets/images/icon button.png
    - assets/images/round.png
    - assets/images/Signup_top.png
    - assets/images/
    - assets/icons/
    - assets/lottie/
