// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xpguwrC796iOhHjeSpVUT64cZkd6pig',
    appId: '1:681239941066:web:a0b5d0971a3986f9c74933',
    messagingSenderId: '681239941066',
    projectId: 'divya-crafts-cbf1b',
    authDomain: 'divya-crafts-cbf1b.firebaseapp.com',
    storageBucket: 'divya-crafts-cbf1b.firebasestorage.app',
    measurementId: 'G-CYFN5DMRVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdp_4blYCnl9eYSQSweOc3RcWGOI_yTPQ',
    appId: '1:681239941066:android:cc039525357ad666c74933',
    messagingSenderId: '681239941066',
    projectId: 'divya-crafts-cbf1b',
    storageBucket: 'divya-crafts-cbf1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_bJlycr6atgcOrJazqCprJyPT_azgO8',
    appId: '1:681239941066:ios:13d2a292c90f2af6c74933',
    messagingSenderId: '681239941066',
    projectId: 'divya-crafts-cbf1b',
    storageBucket: 'divya-crafts-cbf1b.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_bJlycr6atgcOrJazqCprJyPT_azgO8',
    appId: '1:681239941066:ios:13d2a292c90f2af6c74933',
    messagingSenderId: '681239941066',
    projectId: 'divya-crafts-cbf1b',
    storageBucket: 'divya-crafts-cbf1b.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xpguwrC796iOhHjeSpVUT64cZkd6pig',
    appId: '1:681239941066:web:55427c1646cbb030c74933',
    messagingSenderId: '681239941066',
    projectId: 'divya-crafts-cbf1b',
    authDomain: 'divya-crafts-cbf1b.firebaseapp.com',
    storageBucket: 'divya-crafts-cbf1b.firebasestorage.app',
    measurementId: 'G-13PXHC03LN',
  );
}
